### ISSUE TITLE
Documentation of the api wrapper

### ISSUE THREAD

**Issue by Zorbing** [Zorbing/node-lgsdk#7]
Each api function that is available from outside the api wrapper code, should be documented at least by a JSDoc block.
This documentation must contain a description of the function itself, its parameters and their type and the return value.
At the end, the api wrapper which are available at the moment, should be useable from someone who does not has to read the code to use the node-lgsdk package.

## To-Do
- [x] documentation of the functional lcd api
- [x] documentation of the context aware lcd api
- [ ] documentation of the functional g-key api
- [ ] documentation of the context aware g-key api
- [ ] installation instructions in README
- [ ] usage instructions in README
- [x] automatically generated documentation (e.g., in Markdown) from JSDoc comments
